"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol Buffers - Google's data interchange format
Copyright 2023 Google Inc.  All rights reserved.

Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file or at
https://developers.google.com/open-source/licenses/bsd
"""

import builtins
import editions.golden.simple_proto2_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AnotherMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELD_FIELD_NUMBER: builtins.int
    @property
    def field(self) -> editions.golden.simple_proto2_pb2.SimpleProto2: ...
    def __init__(
        self,
        *,
        field: editions.golden.simple_proto2_pb2.SimpleProto2 | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["field", b"field"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["field", b"field"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AnotherMessage: typing_extensions.TypeAlias = AnotherMessage
