"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol Buffers - Google's data interchange format
Copyright 2023 Google Inc.  All rights reserved.

Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file or at
https://developers.google.com/open-source/licenses/bsd
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SimpleProto3(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INT32_FIELD_FIELD_NUMBER: builtins.int
    int32_field: builtins.int
    def __init__(
        self,
        *,
        int32_field: builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["_int32_field", b"_int32_field", "int32_field", b"int32_field"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["_int32_field", b"_int32_field", "int32_field", b"int32_field"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__int32_field: typing_extensions.TypeAlias = typing.Literal["int32_field"]
    _WhichOneofArgType__int32_field: typing_extensions.TypeAlias = typing.Literal["_int32_field", b"_int32_field"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType__int32_field) -> _WhichOneofReturnType__int32_field | None: ...

Global___SimpleProto3: typing_extensions.TypeAlias = SimpleProto3
